# Generated by Django 5.0.2 on 2024-06-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("pdf_resume", models.FileField(upload_to="pdf_resumes/")),
                ("resume_score", models.FloatField(null=True)),
                ("degree_score", models.FloatField(null=True)),
                ("skills_score", models.FloatField(null=True)),
                ("experience_score", models.FloatField(null=True)),
            ],
        ),
    ]
